<!DOCTYPE html>
<html>
<head>
    <title>BUYSELL</title>
</head>
<body>
<h1>BUYSELL</h1><hr>
<h4>Товары со всей России</h4>
<form action="/" method="get">
    Поиск по названию объявления: <input type="text" name="title"><br>
    <input type="submit" value="Поиск"/>
</form>
<#list personalAreas as personalArea>
    <div>
        <p><b>${personalArea.user_id}</b>  руб. | </p>
    </div>
<#else>
    <h3>Товаров нет</h3>
</#list>
<hr>
<h3>Создать новый товар</h3>
<form action="/product/create" method="post" enctype="multipart/form-data">
    Первая фотография: <input type="file" name="file1"/><br><br>
    <input type="submit" value="Добавить картинку"/>
</form>
</body>
</html>